### ISSUE TITLE
Use the base UIBarButtonItem selector for storyboard integration

### ISSUE THREAD

**Issue by jmiglietta-inc** [enmiller/ENMBadgedBarButtonItem-Swift#13]
Instead of replacing the UIBarButtonItem with the embedded UIButton action, modify the class to be truly encapsulated.  This then allows using the Segue generated in the storyboard.  It's a simple modification as shown below:

required init(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)!  
    let image = self.image
    self.button = UIButton(type: .Custom)

```
if let knownImage = image {
    self.button!.frame = CGRectMake(0.0, 0.0, knownImage.size.width, knownImage.size.height)
} else {
    self.button!.frame = CGRectZero;
}

self.button!.setBackgroundImage(image, forState: UIControlState.Normal)
**self.button!.addTarget(self, action: #selector(UIBadgeBarButtonItem.buttonWasTapped(_:)),    
    forControlEvents: UIControlEvents.TouchUpInside)**
    self.customView = button
```

}

extension UIBadgeBarButtonItem {
    internal func buttonWasTapped(sender: UIButton) {
        UIApplication.sharedApplication().sendAction(self.action, to: self.target, from: nil, forEvent: nil)
    }
}

**Comment by enmiller** [comment]
v3 of the library was just released and adds storyboard support.
