### ISSUE TITLE
Carthage Compatability

### ISSUE THREAD

**Issue by zchristopoulos** [enmiller/ENMBadgedBarButtonItem-Swift#24]
It'd be super cool if you included Carthage compatibility. Whenever I try to build it, I get the following error: `Dependency "ENMBadgedBarButtonItem-Swift" has no shared framework schemes for any of the platforms: iOS`

Thanks!

**Comment by enmiller** [comment]
@zchristopoulos I finally have some free time so I will work on Carthage (and SPM) compatibility.

**Comment by enmiller** [comment]
@zchristopoulos Try using version `4.0.2` for Carthage support
