### ISSUE TITLE
Badge won't show up if initialised with non zero badge value.

### ISSUE THREAD

**Issue by ikudriavtsev** [enmiller/ENMBadgedBarButtonItem-Swift#25]
Initialising the `BadgedBarButtonItem` with non zero `startingBadgeValue` will not display a badge.

**Comment by phamvansy** [comment]
Add below line to show badge
`barButton.badgeValue = 1`

**Comment by enmiller** [comment]
@ikudriavtsev This was fixed in `4.0.1` and no longer requires needing to call `barButton.badgeValue = 1` after initialization.  The badge will be displayed with the correct value after initialization is completed.
